version: '2.2'
services:
  node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.20
    container_name: node01
    environment:
      - node.name=node01
      - cluster.name=es-cluster-7
      - discovery.seed_hosts=node01,node02
      - cluster.initial_master_nodes=node01,node02
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-network

  node02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.20
    container_name: node02
    environment:
      - node.name=node02
      - cluster.name=es-cluster-7
      - discovery.seed_hosts=node01,node02
      - cluster.initial_master_nodes=node01,node02
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
      - 9301:9301
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.20
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - node01

volumes:
  es-data01:
    driver: local
  es-data02:
    driver: local

networks:
  es-network:
    driver: bridge  